### model
model_name_or_path: /mnt/nushare2/data/baliao/PLLMs/qwen/Qwen3-1.7B-Base
train_from_scratch: false
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z0_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: tulu_3_sft_mixture_100k
dataset_dir: /mnt/nushare2/data/baliao/dlm/data
template: qwen3
cutoff_len: 4096
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4
neat_packing: true

### output
output_dir: /mnt/nushare2/data/baliao/dlm/01_sft/SFT_100k_AR_Qwen3-1.7B
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]
run_name: SFT_100k_AR_Qwen3-1.7B

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 1
learning_rate: 5.0e-6
num_train_epochs: 2.0
lr_scheduler_type: linear
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500

### acceleration
enable_liger_kernel: True
flash_attn: fa2